FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o focogram .

FROM alpine:latest

WORKDIR /app

RUN apk --no-cache add tzdata
ENV TZ=Asia/Shanghai

COPY --from=builder /app/focogram .
COPY config/config.yml ./config/

EXPOSE 8080

CMD ["./focogram"]
